# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4a6f85af2340bb1c8afb7792b01c4775a29a69b0d356b322930f10e348889667db2baa08a5926526b115c89fce2f129540df4064ff25226bf4120dc8768687f

test:
  secret_key_base: d2c12462036fe66e7897567519aac8ada196c1c46cb5e8d0cc95a18e704876508dbdf965ded7ee89989a360f784642122ace612fc029d0ccc2e9685677d26d5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
